import Flex from "@/shared/UIComponents/Base/Flex";
import Footer from "@/shared/components/Footer/Footer";
import Header from "@/shared/components/Header";
import "@/shared/styles/globals.css";
import "@/shared/styles/tailwindcss-custom.css";
import "@splidejs/react-splide/css/core";
import type { Metadata } from "next";
import GlobalProviders from "../providers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="body bg-transparent  overflow-x-hidden antialiased selection:bg-primary-purple ">
        <GlobalProviders>
          <Header />
          <Flex full className="relative z-2 ">
            {children}
          </Flex>
          <div className="max-w-[768px] lg:max-w-[1280px]  mx-auto  px-8">
            <Footer />
          </div>
          <div className="line-container dark:bg-blackbg bg-white fixed -z-10 w-screen h-screen top-0 left-0 m-0 p-0 overflow-hidden">
            <div className="lines">
              <div className="line"></div>
              <div className="line"></div>
              <div className="line"></div>
            </div>
          </div>
        </GlobalProviders>
      </body>
    </html>
  );
}
