import Flex from "@/shared/UIComponents/Base/Flex";
import Footer from "@/shared/components/Footer/Footer";
import Header from "@/shared/components/Header";
import Subheader from "@/shared/components/Header/Subheader";
import "@/shared/styles/globals.css";
import "@/shared/styles/tailwindcss-custom.css";
import "@splidejs/react-splide/css/core";
import type { Metadata } from "next";
import GlobalProviders from "../providers";
import StarsCanvas from "@/shared/components/StartsCanvas";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body
        id="body-id"
        className="body overflow-x-hidden dark:text-white text-gray-15  antialiased selection:bg-primary-purple relative "
      >
        <GlobalProviders>
          <div className="relative w-full dark:text-white text-gray-15  bg-white dark:bg-blackbg ">
            <Header />
            <StarsCanvas />
            <Subheader />
            <div className="pt-[50px]">{children}</div>
            <Footer />
          </div>
        </GlobalProviders>
      </body>
    </html>
  );
}
